# Generated by Django 4.2.1 on 2023-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_full_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf',
            field=models.FileField(null=True, upload_to='chapter_pdf/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='ppt',
            field=models.FileField(null=True, upload_to='chapter_ppt/'),
        ),
    ]
