# Generated by Django 4.2.1 on 2023-06-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_chapter_pdf_chapter_ppt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='remarks',
            new_name='text',
        ),
    ]
