# Generated by Django 4.2.1 on 2023-06-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_student_email_studentcourseenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
