# Generated by Django 4.2.1 on 2023-06-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='main.teacher'),
        ),
    ]
