# Generated by Django 4.2.1 on 2023-06-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_studentcourseenrollment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf',
            field=models.FileField(null=True, upload_to='store/pdfs/'),
        ),
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
