# Generated by Django 4.2.1 on 2023-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_chapter_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(null=True, upload_to='chapter_videos/'),
        ),
    ]
