# Generated by Django 4.2.1 on 2023-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_chapter_pdf_alter_chapter_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='ppt',
            field=models.FileField(null=True, upload_to='ppts/'),
        ),
    ]
