# Generated by Django 4.2.1 on 2023-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_chapter_ppt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_description',
            field=models.TextField(null=True),
        ),
    ]
