# Generated by Django 4.2.1 on 2023-07-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_attemptquiz_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='techs',
        ),
    ]
